spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgresql
    url: jdbc:postgresql://10.140.0.5:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: 10.146.0.2
    username: guest
    password: guest
    port: 5672

logging.level:
  org.hibernate.SQL: debug