spring:
  datasource:
    url: jdbc:postgresql://10.140.0.5:5432/postgresql
    username: postgresql
    password: postgrespassword
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug